version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Lightsail...
      - echo Logging into ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 418272769848.dkr.ecr.ap-southeast-2.amazonaws.com


  build:
    commands:
      - echo Building Docker image...
      - docker build -t dolloraptor-api-backend .
      - docker tag dolloraptor-api-backend:latest 418272769848.dkr.ecr.ap-southeast-2.amazonaws.com/dolloraptor-api-backend:latest
      - docker push 418272769848.dkr.ecr.ap-southeast-2.amazonaws.com/dolloraptor-api-backend:latest

  post_build:
    commands:
      - echo Creating Lightsail deploy bundle...
      - printf '[{"containerName":"dolloraptor-api-backend-container","image":"418272769848.dkr.ecr.ap-southeast-2.amazonaws.com/dolloraptor-api-backend:latest"}]' > containers.json

      - echo Deploying to Lightsail...
      - aws lightsail create-container-service-deployment \
          --service-name dolloraptor-api-backend-service \
          --containers file://containers.json \
          --public-endpoint '{"containerName":"dolloraptor-api-backend-container","containerPort":8080}' \
          --region ap-southeast-2

artifacts:
  files:
    - containers.json